### ISSUE TITLE
AttributeError: 'Monitor' object has no attribute 'get_constrast'

### ISSUE THREAD

**Issue by brycedjohnson** [newAM/monitorcontrol#10]
Running little test script  on windows 10 python 3.8.2 and python 3.7
 
```
from monitorcontrol import get_monitors

for monitor in get_monitors():
    with monitor:
        print(monitor)
        print(monitor.get_constrast())
```

```
python monitor.py
<monitorcontrol.monitorcontrol.Monitor object at 0x000001AF0A315248>
Traceback (most recent call last):
  File "monitor.py", line 6, in <module>
    print(monitor.get_constrast())
AttributeError: 'Monitor' object has no attribute 'get_constrast
```

**Comment by brycedjohnson** [comment]
Just saw the known issues: Will not work on Windows if you have more than one physical monitor per handle.  I have 3 monitors hooked up so that is likely the issue!

**Comment by newAM** [comment]
> Just saw the known issues: "Will not work on Windows if you have more than one physical monitor per handle." I have 3 monitors hooked up so that is likely the issue!

This is not very clear, sorry about that!
I have tested this with my own 3 monitor setup on Windows, so it should work for you.

I updated the documentation to this:
```
-  Will not work on Windows if you have more than one physical monitor
   per handle.
   per handle.  This typically occurs if you are using NVIDIA surround or AMD
   eyefinity.  This should work in most cases for multi-monitor setups.
```

The issue here is that I am bad at spelling, the `get_constrast` in the example should be `get_contrast`.

A pull-request is here to fix these is here: https://github.com/newAM/monitorcontrol/pull/11

**Comment by newAM** [comment]
The docs should be updated now: https://monitorcontrol.readthedocs.io/en/latest/api.html#monitorcontrol.monitorcontrol.Monitor.get_contrast

Feel free to reopen the issue if this doesn't solve the problem!

**Comment by brycedjohnson** [comment]
Thanks, Lol, I copied the first example and didn't notice the spelling issue!
