### ISSUE TITLE
ValueError: 33 is not a valid InputSource

### ISSUE THREAD

**Issue by Hayleia** [newAM/monitorcontrol#143]
* Monitor manufacturer and model number: MSI Optix MAG342CQRV
* Input source (HDMI, VGA, display port, ect.): HDMI1
* Output device (video card, discrete graphics, ect.): 6800XT
* Operating system: Windows 10 21H1 19043.1466
* Python version: 3.9.9
* monitorcontrol version (`monitorcontrol --version`): 2.5.1

# Steps to Reproduce
```python
import monitorcontrol as mc
monitors = mc.get_monitors()
for monitor in monitors:
	with monitor:
		c = monitor.get_vcp_capabilities()
```
This code crashes with `ValueError: 33 is not a valid InputSource` and I don't get any return from that function.

For more information, on the problematic monitor, `monitor.vcp.get_vcp_capabilities()` returns
```
(prot(monitor)type(lcd)model(MAG342CQRV)cmds(01 02 03 07 0C E3 F3)vcp(02 04 05 08 0B 0C 10 12 14(04 05 08 0B) 16 18 1A 60(00 11 12 0F 21 22 2F 31) CC(02 03 04 05 07 08 09 0A 0C 0D 01 06 0B 0E 12 14 16 17 1A 1E 24) D6(01 04 05) DF FF)mswhql(1)asset_eep(40)mccs_ver(2.2))
```
And indeed in the input source section there is OFF,HDMI1,HDMI2,DP1 (as expected), then there is 21,22,2F,31 and these are not in the enum (and at least the first one crashes).

Are these not standard values?

**Comment by newAM** [comment]
That is an unassigned value, only 0x01 to 0x12 are assigned.  An unassigned value has happened before, but that was with a type-c monitor: https://github.com/newAM/monitorcontrol/issues/93

I'll double check those values are getting parsed correctly when I have time to refresh myself on the spec (probably this weekend).

**Comment by newAM** [comment]
I checked the spec, as far as I can tell `60(00 11 12 0F 21 22 2F 31)` in the VCP capabilities string is invalid, `00` and `21 22 2F 31` are invalid.

The input sources for that monitor are
* 1x DP (1.2)
* 1x HDMI (2.0)
* 1x HDMI (1.4)

which corresponds to the 3 valid bytes (`11 12 0F`).

I am not sure what to do in this situation :thinking:.  The invalid bytes could be ignored, but invalid bytes are also used for inputs that are not (yet) defined by the MCCS specification, such as USB Type-C in #93.  Also the specification is usually explicit when reserved values _should_ be ignored, and it does not use that language for the input source.

**Comment by Hayleia** [comment]
Well I don't really know, especially since I don't know the spec at all.
Maybe an argument that tells if
- they should be ignored 
- they should be returned as integers to be processed by people who know what they're doing
- they should raise an exception (default behaviour I guess)
?

This way, people like me who don't really care about these values can work with standard values instead of having an error and nothing initialized and nothing to work with, and people with USB-C ports can work with them too if they know which one of the non standard values it is?

This kinda sounds like a bad idea of "not deciding what to do" actually, but I don't have better ideas than you about what to do.
