### ISSUE TITLE
File access won't be closed on /dev/i2c

### ISSUE THREAD

**Issue by toefde** [newAM/monitorcontrol#247]
* Input source: HDMI
* Output device: Raspberry Pi 4
* Operating system: Raspberry OS
* Python version: 3
* monitorcontrol version: 3.0.2

Hi, I've got a problem with the python library. 
Everytime I execute `monitorcontrol.get_monitors()` it accesses the file (in my case) `/dev/i2c-21` with a new file descriptor. 
I need to execute it every second and after a few hundred iterations my script crashes with _[Errno 24] Too many open files_. Because there is a limit of open files on the system (Yes, I could increase the limit, but it won't help) is it possible to dispose whatever the library does there? I need to somehow evade this problem. 

Thanks for the help

**Comment by newAM** [comment]
I'm pretty busy this weekend, but I can try to take a look next weekend.  This was the first python library I wrote, it's likely that there's just something sub-optimal somewhere :)

Do you have some simple code I can use to reproduce this?

**Comment by newAM** [comment]
Thanks for that reproduction, that was very helpful!

This is indeed a bug.  When exceptions were generated, which occurred for non-monitor devices on the i2c bus `__exit__` never got called and the file descriptors never got closed.

I normally wait for feedback, on fixes, but I'm pretty confident that #252 fixes this, so I'll merge that and cut a release.  If that doesn't fix it let me know and I can do another release!
