### ISSUE TITLE
Error Running with Windows Task Scheduler

### ISSUE THREAD

**Issue by avenzi** [newAM/monitorcontrol#274]
# Info:
Manufacturer: Dell
Model: U2719D
Input Source: HDMI
Output Device: Nvidia card
OS: Windows 11
Python version: 3.9.0
Monitorcontrol version: 3.0.3

# Steps to Reproduce

1. Write a simple script and make sure it works when running normally with python. Make sure to output any errors to a file because you can't see stdout when running with the task scheduler. Here is a working example:
```
from monitorcontrol import get_monitors
import traceback

LOGFILE = "D:\Desktop\example.log"

def log(msg):
    """ log to a file """
    with open(LOGFILE, 'a') as f:
        f.write(msg+'\n')

try:
    monitors = get_monitors()
    log(f"Found {len(monitors)} monitors")
    for monitor in monitors:
        with monitor:  # <--- Error happens here
            info = monitor.get_vcp_capabilities()
except Exception as e:
    log(f"Error: {traceback.format_exc()}")
```
When this runs normally, you should see an output like `Found 2 monitors` in the output file.

2. Open windows task scheduler and click "Create Basic Task" and provide a name and trigger interval, neither of which impact the bug.
3. In the "Action" section, select "Start a program".
4. In the "Program/script" field, enter the absolute path to your python executable (note that if the monitorcontrol package is in a virtual environment, the executable should be from that virtual environment). Example: `D:\Desktop\myproject\venv\Scripts\python.exe`
5. In the "Add arguments" field, put the absolute path to the python script. Example: `D:\Desktop\myproject\test.py`
6. Finish creating the task. You may need to specify your user password - note that it's your password and not your user PIN. (took me awhile to realize that).
7. Select the task from the list
8. On the right-hand side, click "Run" to run the task manually
9. Now check the output file. Here is what I get:
```
Found 1 monitors
Error: Traceback (most recent call last):
  File "D:\Desktop\Repositories\Python\OSC-to-DDCCI\test2.py", line 16, in <module>
    with monitor:  # <--- Error happens here
  File "D:\Desktop\Repositories\Python\OSC-to-DDCCI\venv\lib\site-packages\monitorcontrol\monitorcontrol.py", line 84, in __enter__
    self.vcp.__enter__()
  File "D:\Desktop\Repositories\Python\OSC-to-DDCCI\venv\lib\site-packages\monitorcontrol\vcp\vcp_windows.py", line 50, in __enter__
    raise VCPError("no physical monitor found")
monitorcontrol.vcp.vcp_abc.VCPError: no physical monitor found
```

EDIT: added some missing steps to creating a task

**Comment by newAM** [comment]
Thanks for the through bug report!

Sadly I'm not sure what is going on here, this is a little beyond my Windows knowledge.

Random guesses:
1. The process run by task scheduler has insufficient permissions to interact with this hardware.
2. Windows associates monitors with a desktop session, and some environment variable needs to be forwarded to the task for a headless task to interact with the monitors.

I'm curious to know what would cause this if you figure it out!

**Comment by avenzi** [comment]
I figured it out! Turns out you need to select the option "Run only when user is logged on" in task scheduler. I think you were right on both accounts - if you instead select "Run whether user is logged on or not", I believe windows doesn't grant is access to certain systems, causing the error. Now I've just gotta figure out how to prevent it from popping up a command window...
