### ISSUE TITLE
Erratic ValueError raised in get_power_mode()

### ISSUE THREAD

**Issue by gabortim** [newAM/monitorcontrol#289]
* Monitor manufacturer and model number: **Dell U2415**
* Input source (HDMI, VGA, display port, ect.): **via passive DVI-D -> HDMI cable**
* Output device (video card, discrete graphics, ect.): **Nvidia GTX 1050 Ti**
* Operating system: **Windows 10 (build 19045.3448)**
* Python version: **3.11.6**
* monitorcontrol version (`monitorcontrol --version`): **3.0.3**

# Steps to Reproduce

1. Start this snippet:
    ```py
      import time
      
      from monitorcontrol import get_monitors
      
      if __name__ == '__main__':
          while True:
              for i, monitor in enumerate(get_monitors()):
                  with monitor:
                      print(f"Monitor #{i}: {monitor.get_power_mode()}")
                      time.sleep(3)
    ```
2. Wait until the display goes into standby, the issue should pop up after some time. It seems nondeterministic.
3. Here the `self._get_vcp_feature(code)` returns zero, then `PowerMode(value)` called with this 0 which raises `{ValueError}0 is not a valid PowerMode`

https://github.com/newAM/monitorcontrol/blob/a363456ea17887d57244d9ff511901d9f9325f22/monitorcontrol/monitorcontrol.py#L378-L401

```
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\JetBrains\PyCharm2023.2\scratches\scratch_1.py", line 9, in <module>
    print(f"Monitor #{i}: {monitor.get_power_mode()}")
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\monitor\venv\Lib\site-packages\monitorcontrol\monitorcontrol.py", line 324, in get_power_mode
    return PowerMode(value)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 0 is not a valid PowerMode
```

#288 Seems related.

**Comment by newAM** [comment]
Could also be related to #117.

Does this only occur in standby mode?  There are a number of monitors that simply don't respond to DDC-CI commands in standby.  It is strange that this is erratic though.  Perhaps check if there are some monitor power features you can tweak?

**Comment by gabortim** [comment]
Yes, I've only seen it after the display entered standby. I'm going to profile it a bit more, maybe I'll find some patterns that help debug the case.

**Comment by gabortim** [comment]
When I wait for Windows to put the display in sleep, it's erratic.
When I explicitly set `monitor.set_power_mode(PowerMode.off_soft)`, it instantly reproduces with this snippet:

```py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time

from monitorcontrol import get_monitors, VCPError, PowerMode
from winsound import Beep

if __name__ == '__main__':
    monitor = get_monitors()[0]
    with monitor:
        monitor.set_power_mode(PowerMode.off_soft)

    while True:
        for i, monitor in enumerate(get_monitors()):
            with monitor:
                try:
                    print(f"Monitor #{i}: {monitor.get_power_mode()}")
                    time.sleep(3)
                except (VCPError, ValueError) as e:
                    while True:
                        Beep(450, 400)
                        time.sleep(0.1)
```

Also, I updated to monitorcontrol 3.1.0 and the trace changed a bit:

```
Traceback (most recent call last):
  File "D:\Projects\monitor\test\test_offline.py", line 18, in <module>
    print(f"Monitor #{i}: {monitor.get_power_mode()}")
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\monitor\venv\Lib\site-packages\monitorcontrol\monitorcontrol.py", line 390, in get_power_mode
    value = self._get_vcp_feature(code)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\monitor\venv\Lib\site-packages\monitorcontrol\monitorcontrol.py", line 184, in _get_vcp_feature
    current, maximum = self.vcp.get_vcp_feature(code.value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\monitor\venv\Lib\site-packages\monitorcontrol\vcp\vcp_windows.py", line 135, in get_vcp_feature
    raise VCPError("failed to get VCP feature: " + ctypes.FormatError())
monitorcontrol.vcp.vcp_abc.VCPError: failed to get VCP feature: A művelet meghiúsult, mert a DDC/CI-üzenet parancsmezője érvénytelen értéket tartalmazott.
```

Which resembles https://github.com/newAM/monitorcontrol/issues/288#issuecomment-1753623855. I think I'm out of luck, but at least I know the issue is in my hardware.

**Comment by gabortim** [comment]
Changing closure state.
