### ISSUE TITLE
AttributeError: 'WindowsVCP' object has no attribute 'handle'

### ISSUE THREAD

**Issue by YsGrandi** [newAM/monitorcontrol#4]
```
import monitorcontrol

monitors = monitorcontrol.get_monitors()
print(monitors[0].get_power_mode())
```
don't know why this error is hapening

**Comment by newAM** [comment]
Can you copy and paste the entire traceback?

**Comment by newAM** [comment]
Oh, that wont be necessary, I looked at the code.

The context manager needs to be used,

```python
for monitor in get_monitors():
    with monitor:
        print(monitor.get_power_mode())
```

I should improve that error message though.

**Comment by newAM** [comment]
Added an assertion in version 2.1.0 and added more examples to the documentation, closing.
