### ISSUE TITLE
USB-C InputMode not supported

### ISSUE THREAD

**Issue by MinaHany** [newAM/monitorcontrol#93]
Thanks a lot for this work, it is very handy!

I have a Dell U2720Q and when it is on the "USB-C" input, I get an error message trying to read the input mode:

`ValueError: 27 is not a valid InputSource`

**Comment by newAM** [comment]
![image](https://user-images.githubusercontent.com/7845120/122645648-32dc3780-d0d0-11eb-8d7f-4d76387abc71.png)

I think the specification has not kept up with the technology, that is from the MCCS v2.2a (latest), 27 (0x1B) is a reserved value.
I would rather not depart from the specification unfortunately, I have no idea if that is a pseudo standard or vendor specific.

**Comment by MinaHany** [comment]
You seem to be right that it is vendor specific. What could be a good solution here? Will you consider adding a way for users to define their custom inputs? Something like:
`create_custom_input_source("USB-C", "0x1B")`

**Comment by newAM** [comment]
Yeah; I am happy to add something to make this usable in the meantime for sure :+1: 

> Will you consider adding a way for users to define their custom inputs? Something like: create_custom_input_source("USB-C", "0x1B")

This would be nice, but unfortunately enums (type of `InputSource`) are non-mutable in python, so it would require a breaking change to the API to enable this, which I would like to avoid if there is another way.

---

Are you using the command line interface or the API?

For the API side I have some ideas; let me know what you think!

`set_input_source` can take an input - but it tries to cast it to an `InputSource` first - that can simply be removed, allowing people to set `0x1B` on monitors where it is reserved should not have any significant adverse impacts.

`get_input_source` can subclass `ValueError` so the error value is accessible, for example (type hints added for clarity):
```py
try:
    input_source: InputSource = monitor.get_input_source()
except VcpValueError as e:
    input_source_val: int = e.value
else:
    input_source_val: int = input_source.value
```

**Comment by MinaHany** [comment]
Sounds good: try to use one of the defined InputSource, if it can't, just return the hex value.
Thank you for doing this, much appreciated!

**Comment by MinaHany** [comment]
I am using the API btw

**Comment by newAM** [comment]
I opened a PR to fix this here: https://github.com/newAM/monitorcontrol/pull/94

Let me know if that fixes this and I'll merge it in.

**Comment by MinaHany** [comment]
I think that looks good, thank you very much!
Will I be able to set the inputmode to 27 as well with this?

**Comment by newAM** [comment]
Yup!
Should work with `monitor.set_input_source(27)`

I'll merge it in and get a release going.

**Comment by MinaHany** [comment]
Thank a lot for this, just had a chance to try it out today.
It looks like I cannot import InputSourceValueError for some reason. 
I get `ImportError: cannot import name 'InputSourceValueError' from 'monitorcontrol'`
Any idea why?

**Comment by newAM** [comment]
Yeah it is under `monitorcontrol.monitorcontrol`.  i'll re-export it to the root next release.

**Comment by MinaHany** [comment]
Cheers, thank you!
